'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class unutrasnjiResursi
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_06._GAME__BombardovanjePodgorice.unutrasnjiResursi", GetType(unutrasnjiResursi).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property _logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property _maliLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_maliLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property _pozadina() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_pozadina", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property karBblack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("karBblack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property karBdim() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("karBdim", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property karPlane() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("karPlane", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property karSjenka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("karSjenka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_igrac_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_igrac_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_najboljiRez_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_najboljiRez_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_poruka_neprocitano() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_poruka_neprocitano", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_poruka_od() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_poruka_od", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_poruka_procitano() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_poruka_procitano", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_poruka_za() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_poruka_za", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_poruke_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_poruke_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_poruke_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_poruke_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_rezuktati_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_rezuktati_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_rezuktati_bronza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_rezuktati_bronza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_rezuktati_srebro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_rezuktati_srebro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_rezuktati_zlato() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_rezuktati_zlato", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_sviIgraci_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_sviIgraci_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_sviIgraci_offline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_sviIgraci_offline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property konzola_sviIgraci_online() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("konzola_sviIgraci_online", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property kucBomb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kucBomb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property kucNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kucNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property login_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property login_registracija() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_registracija", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property login_standard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_standard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property login_tabs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_tabs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property login_ulazak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_ulazak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property mapPG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapPG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property mapPGover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapPGover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property meni_poruka_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meni_poruka_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property menu_bezBaze() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_bezBaze", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property menu_bezBaze_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_bezBaze_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property menu_saBazom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_saBazom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property menu_ucitavanje() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_ucitavanje", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property satus_vrijeme_bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("satus_vrijeme_bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property statu_vrijeme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("statu_vrijeme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property status_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("status_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property status_bomba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("status_bomba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property status_pomoc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("status_pomoc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
